language: objective-c
osx_image: xcode7

before_script:
- brew install carthage
- carthage update --use-ssh
script:
- xctool -project Shipbit.xcodeproj -scheme Shipbit -sdk iphonesimulator build test

