language: objective-c
osx_image: xcode7

before_script:
- gem install xcpretty
- brew install carthage
- carthage update
script:
- xcodebuild test -project Shipbit.xcodeproj -scheme Shipbit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
